### ISSUE TITLE
Make the Navbar Responsive

### ISSUE THREAD

**Issue by Dhruv-Sood** [Dhruv-Sood/clockomoro#1]
Currently, the navigation bar displays "Home," "About," and "Contribute" links. However, on smaller screens, we want to hide these links and replace them with a hamburger icon ☰ that reveals a collapsible menu when clicked.

**Tasks:**
- Implement a responsive design for the navigation bar using media queries to target smaller screens (e.g., mobile devices).
- Replace the "Home," "About," and "Contribute" links with a hamburger icon ☰.
- Make sure to adhere to the project's contributing guidelines.

**Note:** Please avoid making changes to the overall project's style, as a separate issue will be created for any style-related enhancements.

Clockomoro is designed to be a friendly environment for new contributors to learn and grow in the open-source community. Your efforts in making the navigation bar responsive will significantly improve the user experience for developers using the Pomodoro Technique.

Thank you for your contribution! Happy coding! ☺️

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by Dhruv-Sood** [comment]
@anubhav1206  All yours😊
