### ISSUE TITLE
[BUG] Start timer button is not styled in light mode

### ISSUE THREAD

**Issue by Dhruv-Sood** [Dhruv-Sood/clockomoro#11]
The start timer button in TimerPage.jsx is not styled in light mode
<img width="870" alt="Screenshot 2023-08-09 at 9 27 11 PM" src="https://github.com/Dhruv-Sood/clockomoro/assets/114243833/31374252-bef1-4b55-8f2f-f809cda06fb7">

Add a dark background,And on hover: cursor and opacity change

Kindly adhere to the contributions guidlines

**Comment by keshavsinha17** [comment]
Is this issue still up for grabs? I think it's solved.

**Comment by Dhruv-Sood** [comment]
@keshavsinha17 This issue has been solved in the previous PR
