### ISSUE TITLE
Generate typing animation in Logo

### ISSUE THREAD

**Issue by Dhruv-Sood** [Dhruv-Sood/clockomoro#4]
-> Generate typing animation in CLOCKOMORO logo in navbar, the animation should work only once when the site loads
-> Kindly adhere to the contributing guidelines mentioned in README

**Comment by abhinavrathore25** [comment]
Can I work on this issue?

**Comment by Dhruv-Sood** [comment]
@abhinavrathore25 Sure!!

**Comment by Dhruv-Sood** [comment]
@abhinavrathore25 Any updates?
Do notify if you are not working on this issue, I can assign it to someone else

**Comment by abhinavrathore25** [comment]
Yes I am working on the issue.

**Comment by abhinavrathore25** [comment]
Hey @Dhruv-Sood ,

https://github.com/Dhruv-Sood/clockomoro/assets/50289245/7f38c22f-12ea-4dbf-9c28-1322bae4d51e

If the above changes are acceptable to you i'll create a PR.

**Comment by Dhruv-Sood** [comment]
Looks good!!....Can we get rid of the cursor once the animation ends?

**Comment by abhinavrathore25** [comment]
Sure we can!
Do you want the cursor to disappear as soon as the effect ends, or you want it to blink once and then remove it?

**Comment by Dhruv-Sood** [comment]
Whichever looks better.... that's on you 😊

**Comment by abhinavrathore25** [comment]
I have changed it to blink once and remove 😊
You can change the time of setTimeout function according to your convenience to manipulate cursor visibility.

I have created a pull request. Please review ..!

**Comment by Dhruv-Sood** [comment]
Wow!!
I didn't Know there's a package to provide typewriter effect....Thanks for this valuable contribution @abhinavrathore25 😊
Mind giving this project a ⭐️? I'm trying to create new issues in this project to help everyone learn react and opensource😊

**Comment by abhinavrathore25** [comment]
Most welcome @Dhruv-Sood,
I did it first with manual code but it seemed unnecessary so I switched to library.

Ps. I gave your repo a star ⭐️
